openapi: 3.0.0
info:
  title: WebService130
  version: 1.0.0
servers:
  - url: https://130.162.195.228/mhs714220006
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /regis:
    post:
      tags:
        - default
      summary: UasRegis
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                username:
                  type: string
                  example: balqis
                password:
                  type: string
                  example: Balqis123
                email:
                  type: string
                  example: balqisrosa@gmail.com
                phone_number:
                  type: string
                  example: '083154664118'
                address:
                  type: string
                  example: Jl.Adikusumah Bandung
      responses:
        '200':
          description: Respon Berhasil
          content:
            application/json: {}
  /login:
    post:
      tags:
        - default
      summary: UserLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                username:
                  type: string
                  example: balqis
                password:
                  type: string
                  example: Balqis123
                email:
                  type: string
                  example: balqisrosa@gmail.com
                phone_number:
                  type: string
                  example: '083154664118'
                address:
                  type: string
                  example: Jl.Adikusumah Bandung
      responses:
        '200':
          description: Respon Berhasil
          content:
            application/json: {}
  /products:
    get:
      tags:
        - default
      summary: Produk
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Respon Berhasil
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: TambahProduk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: T-shirt
                price:
                  type: integer
                  example: 200000
                stock:
                  type: integer
                  example: 1
                description:
                  type: string
                  example: t-shirt limited edition
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Respon Berhasil
          content:
            application/json: {}
  /products/{id}:
    put:
      tags:
        - default
      summary: UpdateProduk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: T-shirt
                price:
                  type: integer
                  example: 200000
                stock:
                  type: integer
                  example: 2
                description:
                  type: string
                  example: t-shirt limited edition
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Respon Berhasil
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: HapusProduk
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Respon Berhasil
          content:
            application/json: {}
  /orders:
    get:
      tags:
        - default
      summary: Pesanan
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Respon Berhasil
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: TambahPesanan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  example: 3
                total:
                  type: integer
                  example: 250000
                status:
                  type: string
                  example: Sukses
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Respon Berhasil
          content:
            application/json: {}
  /orders/{id}:
    put:
      tags:
        - default
      summary: UpdatePesanan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  example: 3
                total:
                  type: integer
                  example: 250000
                status:
                  type: string
                  example: gagal
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Respon Berhasil
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: HapusPesanan
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Respon Berhasil
          content:
            application/json: {}